// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0tlpvWGIDL_3OfD_mYmRwY-a2_rMJXk4',
    appId: '1:478320382979:web:fdf361c3daff44dc2aaa36',
    messagingSenderId: '478320382979',
    projectId: 'cakesecurity-d9790',
    authDomain: 'cakesecurity-d9790.firebaseapp.com',
    storageBucket: 'cakesecurity-d9790.firebasestorage.app',
    measurementId: 'G-840MJP034D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdxlqlax4DlxzPvJu9mGerk8jC3SvZLUU',
    appId: '1:478320382979:android:dc3387b0a053053d2aaa36',
    messagingSenderId: '478320382979',
    projectId: 'cakesecurity-d9790',
    storageBucket: 'cakesecurity-d9790.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTGI-85mcFUDt4FC68XrKTKG6gHrtVhUM',
    appId: '1:478320382979:ios:bbb90f2cd0fd08252aaa36',
    messagingSenderId: '478320382979',
    projectId: 'cakesecurity-d9790',
    storageBucket: 'cakesecurity-d9790.firebasestorage.app',
    iosBundleId: 'com.example.appProprietaire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTGI-85mcFUDt4FC68XrKTKG6gHrtVhUM',
    appId: '1:478320382979:ios:bbb90f2cd0fd08252aaa36',
    messagingSenderId: '478320382979',
    projectId: 'cakesecurity-d9790',
    storageBucket: 'cakesecurity-d9790.firebasestorage.app',
    iosBundleId: 'com.example.appProprietaire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0tlpvWGIDL_3OfD_mYmRwY-a2_rMJXk4',
    appId: '1:478320382979:web:43a5ab1336372b572aaa36',
    messagingSenderId: '478320382979',
    projectId: 'cakesecurity-d9790',
    authDomain: 'cakesecurity-d9790.firebaseapp.com',
    storageBucket: 'cakesecurity-d9790.firebasestorage.app',
    measurementId: 'G-90Y08X8DES',
  );
}
